### ISSUE TITLE
Exception: Could not deserialize ATN with version  (expected 4).

### ISSUE THREAD

**Issue by zergulaydin** [loodos/zemberek-python#8]
from zemberek import (
    TurkishSpellChecker,
    TurkishSentenceNormalizer,
    TurkishSentenceExtractor,
    TurkishMorphology,
    TurkishTokenizer
)
için  def readATN(self):

Exception: Could not deserialize ATN with version  (expected 4). hatasını alıyorum.

**Comment by BugraHamza** [comment]
The error is because of the version of the _antlr4-python3-runtime_ package.
I solved the issue by downgrading _antlr4-python3-runtime_ to _4.8_

`pip install antlr4-python3-runtime==4.8`

**Comment by zergulaydin** [comment]
Thanks, problem solved.
